name: All Unit Tests
on:
  workflow_call:

jobs:
  unit_tests:
    name: All Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Setup/prelims
      - name: Checkout
        uses: actions/checkout@v4

      # Disable AppArmor to allow Chrome/Puppeteer to run in the container.
      # Ripped from https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/daily.yml
      # See also: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      # Build all packages.
      - name: Build
        run: npm -ws run build

      # Run unit tests in all workspaces.
      - name: "All unit tests"
        run: npm -ws test